# Generated by Django 5.2.14 on 2026-05-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='ID from attendance machine', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='ID from attendance machine', max_length=50, null=True, unique=True),
        ),
    ]
