# Generated by Django 5.2.14 on 2026-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_biometric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Photo'),
        ),
    ]
