# Generated by Django 5.2.14 on 2026-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_photo_teacherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_coordinator',
            field=models.BooleanField(default=False, help_text='Coordinators can evaluate teachers and have a separate KPI framework.', verbose_name='Is Coordinator'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='biometric_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from attendance machine', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='biometric_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from attendance machine', max_length=50, null=True, unique=True),
        ),
    ]
