# Generated by Django 5.2.14 on 2026-06-06 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date this lesson will be delivered')),
                ('duration', models.CharField(help_text='e.g. 45 minutes', max_length=50)),
                ('main_topic', models.CharField(help_text='The broad topic this lesson belongs to', max_length=200)),
                ('lesson_title', models.CharField(help_text='Specific title for this lesson', max_length=200)),
                ('learning_objectives', models.TextField(help_text='What students will be able to do by the end')),
                ('prior_knowledge', models.TextField(help_text='What students already know that this lesson builds on')),
                ('resources', models.TextField(help_text='Materials, textbooks, digital tools, etc.')),
                ('starter', models.TextField(help_text='Warm-up or hook activity (5–10 min)')),
                ('main_lesson', models.TextField(help_text='Core instruction / teacher-led content')),
                ('activities', models.TextField(help_text='Student tasks and exercises')),
                ('differentiation', models.TextField(help_text='Support for SEN / extension for higher ability')),
                ('plenary', models.TextField(help_text='Wrap-up, review, and assessment of learning')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Coordinator feedback or rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'coordinator']}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
