# Generated by Django 5.2.14 on 2026-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='date',
            field=models.DateField(db_index=True, help_text='Date this lesson will be delivered'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=15),
        ),
    ]
