# Generated by Django 5.2.14 on 2026-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_description',
            field=models.CharField(blank=True, help_text='e.g., Sibling Discount, Merit Scholarship', max_length=200),
        ),
    ]
