# Generated by Django 4.2.30 on 2026-10-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoice_issued_date_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fee_month',
            field=models.CharField(blank=True, default='', help_text="Optional: adds 'Fees of the month of [Month]' text to the invoice", max_length=20),
        ),
    ]
