# Generated by Django 5.2.14 on 2026-05-12 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator')], max_length=15)),
                ('name', models.CharField(help_text='e.g., Timeliness, Academic Quality', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what is measured')),
                ('data_source', models.CharField(help_text="Where data comes from, e.g., 'Attendance system', 'HOD observation', 'Student survey'", max_length=200)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Weight as percentage, e.g. 15.00 for 15%. All KPIs for a role must total 100.', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance.kpisection')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Term 1 — 2025-26 Performance Review'", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kpisection',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='performance.performancecycle'),
        ),
        migrations.CreateModel(
            name='StaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator')], max_length=15)),
                ('overall_comment', models.TextField(blank=True, help_text="Evaluator's overall remarks")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated weighted score out of 100', max_digits=5, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='performance.performancecycle')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff__first_name', 'staff__last_name'],
            },
        ),
        migrations.CreateModel(
            name='KPIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score 0–100 for this KPI', max_digits=5)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='performance.kpi')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_scores', to='performance.staffevaluation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffevaluation',
            constraint=models.UniqueConstraint(fields=('cycle', 'staff'), name='unique_staff_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='kpiscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'kpi'), name='unique_kpi_score_per_eval'),
        ),
    ]
