# Generated by Django 5.2.14 on 2026-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/Principal'), ('coordinator', 'Coordinator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('accounts', 'Accounts')], default='student', max_length=15, verbose_name='Role'),
        ),
    ]
