# Generated by Django 5.2.14 on 2026-05-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='e.g., A+, A, B+, B', max_length=5)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum percentage', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage', max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=1, default=0, help_text='GPA point value', max_digits=3)),
                ('remark', models.CharField(blank=True, help_text='e.g., Excellent, Good, Needs Improvement', max_length=50)),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='SubjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('comment', models.TextField(help_text="Teacher's remark for this student in this subject")),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_given', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_comments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'section', 'academic_year'), name='unique_subject_comment')],
            },
        ),
    ]
