# Generated by Django 5.2.14 on 2026-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_seed_class_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrecord',
            name='date_conducted',
            field=models.DateField(db_index=True),
        ),
    ]
