# Generated by Django 5.2.14 on 2026-05-12 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_assessmentrecord_date_conducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026', max_length=10, unique=True)),
                ('mode', models.CharField(choices=[('quarterly', 'Quarterly (4 Reports)'), ('term', 'Term (2 Reports — Mid & Final)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 1st Quarter, Mid-Term', max_length=50)),
                ('sequence', models.PositiveIntegerField(help_text='Display order: 1, 2, 3, 4')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, help_text='If checked, visible to students/parents')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='exams.academicperiodconfig')),
            ],
            options={
                'ordering': ['config', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PeriodWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 20.00 for 20%', max_digits=5)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.assessmenttype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightings', to='exams.reportperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportperiod',
            constraint=models.UniqueConstraint(fields=('config', 'sequence'), name='unique_period_sequence'),
        ),
        migrations.AddConstraint(
            model_name='periodweighting',
            constraint=models.UniqueConstraint(fields=('period', 'assessment_type'), name='unique_period_weight'),
        ),
    ]
