# Generated by Django 5.2.14 on 2026-05-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('exams', '0005_academicperiodconfig_reportperiod_periodweighting_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodweighting',
            name='unique_period_weight',
        ),
        migrations.AddField(
            model_name='periodweighting',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Leave blank for default weights. Set for subject-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='periodweighting',
            constraint=models.UniqueConstraint(fields=('period', 'assessment_type', 'subject'), name='unique_period_subject_weight'),
        ),
    ]
