# Generated by Django 5.2.14 on 2026-06-02 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear'),
        ('exams', '0006_remove_periodweighting_unique_period_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectcomment',
            name='unique_subject_comment',
        ),
        migrations.AddField(
            model_name='subjectcomment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exams.reportperiod'),
        ),
        migrations.AddConstraint(
            model_name='subjectcomment',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'section', 'academic_year', 'period'), name='unique_subject_comment_period'),
        ),
    ]
