# Generated by Django 5.2.14 on 2026-05-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavepolicy',
            options={'ordering': ['-academic_year__start_date', 'leave_type__name'], 'verbose_name_plural': 'Leave Policies'},
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='allocated_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days allocated per year'),
        ),
    ]
