# Generated by Django 5.2.14 on 2026-05-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leavepolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Required for Early Leave', null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='category',
            field=models.CharField(choices=[('advance', 'Advance Leave'), ('emergency', 'Emergency Leave'), ('early', 'Early Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype'),
        ),
    ]
