# Generated by Django 5.2.14 on 2026-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaveapplication_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('coordinator_approved', 'Coordinator Approved'), ('admin_approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=25),
        ),
    ]
