# Generated by Django 5.2.14 on 2026-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
