# Generated by Django 5.2.14 on 2026-06-08 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
