# Generated by Django 5.2.14 on 2026-05-21 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear'),
        ('attendance', '0003_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_attendance'),
        ),
    ]
